const translations = {
  home: {
    ru: {
      meta_title: 'Виталий Крумин — AI Product / Applied AI / Research',
      meta_description: 'Виталий Крумин — AI Product Manager и research-driven strategist. Проектирую и запускаю Applied AI, продуктовые системы, CRM-контуры и growth-механики, которые доходят до измеримого результата.',
      'brand.role': 'AI Product • Applied AI • Research',
      'nav.value': 'Ценность',
      'nav.cases': 'Кейсы',
      'nav.publications': 'Публикации',
      'nav.career': 'Карьера',
      'nav.contacts': 'Контакты',
      'topbar.cta': 'Написать',
      'hero.eyebrow': 'AI Product Manager • Research-driven architect • Applied AI systems',
      'hero.title': 'Соединяю <span>research</span>, <span>product</span> и <span>applied AI</span> в бизнес системы.',
      'hero.lead': 'Я полезен там, где нужно навести порядок в сложной задаче, перевести идею в продуктовую архитектуру, собрать рабочий AI-контур и довести его до внедрения, метрик и понятной бизнес-ценности.',
      'hero.ctaPrimary': 'Написать в Telegram',
      'hero.ctaSecondary': 'Смотреть кейсы',
      'hero.ctaTertiary': 'Карьерный путь',
      'hero.tag1': 'Applied AI & LLM workflows',
      'hero.tag2': 'Product discovery & MVP design',
      'hero.tag3': 'Research, analytics & hypotheses',
      'hero.tag4': 'CRM, growth & customer journeys',
      'hero.metric1': 'лет в продуктах, маркетинге, росте и развитии',
      'hero.metric2': 'участников в запущенных обучающих программах',
      'hero.metric3': 'рост обращений в одном из контентных контуров',
      'portrait.label': 'Портрет / personal presence',
      'portrait.title': 'От идеи и исследования — к продукту, росту и внедрению AI.',
      'portrait.text': 'Стратег, исследователь, продуктовый архитектор AI-решений.',
      'signal.label': 'Где я особенно силен',
      'signal.title': 'Не просто про AI. Про систему, которая работает после демо',
      'signal.item1': 'Research synthesis',
      'signal.item2': 'Product architecture',
      'signal.item3': 'LLM orchestration',
      'signal.item4': 'CRM scenarios',
      'signal.item5': 'Growth loops',
      'signal.item6': 'MVP delivery',
      'signal.status': 'Открыт к сильным задачам на стыке AI Product, strategy, research и systems design',
      'impact.kicker': 'Что ты получаешь, когда я в проекте',
      'impact.title': 'Не набор красивых слов, а человека, который может собрать хаос в работающую логику',
      'impact.card1.title': 'Нахожу сигнал в шуме',
      'impact.card1.text': 'Провожу ресерч, вытаскиваю главное из разрозненных вводных, формулирую настоящую проблему и точку роста.',
      'impact.card2.title': 'Собираю архитектуру решения',
      'impact.card2.text': 'Перевожу идеи на язык продукта, сценариев, процессов, данных и AI-workflows, которые можно реально запускать.',
      'impact.card3.title': 'Дотягиваю до внедрения и эффекта',
      'impact.card3.text': 'Думаю не только о механике, но и о принятии, метриках, масштабировании и том, как решение живет после запуска.',
      'cases.kicker': 'Избранные кейсы',
      'cases.title': 'Там, где встретились продукт, рост, исследование и applied AI',
      'cases.case1.pill': 'Education + AI + CRM',
      'cases.case1.title': 'Контентные и AI-проекты для агентов недвижимости',
      'cases.case1.text': 'Запустил обучающие механики, контентный контур и AI-практики для агентов. Система работала не на “охваты ради охватов”, а на обращения, лиды и сделки.',
      'cases.case1.r1': 'подписчики выросли на 70%',
      'cases.case1.r2': 'обращения выросли в 4 раза',
      'cases.case1.r3': 'сделки из соцсетей выросли в 2 раза',
      'cases.case2.pill': 'Applied AI / Agentic workflow',
      'cases.case2.title': 'AI-агент для ресерча и Google Workspace',
      'cases.case2.text': 'Собрал рабочий контур на базе Perplexity API и ChatGPT API для ресерча, документов, почты, календаря и Drive — как единую операционную среду, а не набор разрозненных ботов.',
      'cases.case2.r1': 'ускорение исследовательских задач',
      'cases.case2.r2': 'единая точка для операционных сценариев',
      'cases.case2.r3': 'снижение ручной нагрузки в рутинных процессах',
      'cases.case3.pill': 'Product / CRM / Growth',
      'cases.case3.title': 'living.ru — продукт “Вторичка” и CRM-сценарии',
      'cases.case3.text': 'Развивал продуктовые направления, региональный сервис и CRM для продаж и контакт-центра. Работал на стыке ресерча, продуктовой логики и роста.',
      'cases.case3.r1': 'новый продукт дал рост среднего чека на 30%',
      'cases.case3.r2': 'конверсия в сделку выросла до 15%',
      'cases.case3.r3': 'доля CPC-трафика выросла до 30%, CAC снизился на 10%',
      'cases.case4.pill': 'Research / Frameworks',
      'cases.case4.title': 'Исследования Applied AI и собственные frameworks',
      'cases.case4.text': 'Провел серию исследований, опубликовал материалы в Zenodo и развивал framework-логику вокруг AI, человеческой ценности, организационных эффектов и продуктовой архитектуры.',
      'cases.case4.r1': 'публикации с DOI на Zenodo',
      'cases.case4.r2': 'framework-мышление вместо набора случайных тезисов',
      'cases.case4.r3': 'глубокая связка ресерча, бренда и системного дизайна',
      'pubs.kicker': 'Публикации',
      'pubs.title': 'Когда нужно не только строить, но и думать глубже среднего',
      'pubs.note': 'Отдельная линия — монография “Рефлексивный бренд” и собственные frameworks, где AI, идентичность, поведение и продуктовая архитектура сходятся в одну систему.',
      'stack.kicker': 'Рабочий стек',
      'stack.title': 'Набор, из которого собирают не просто идеи, а работающие контуры',
      'stack.item1': 'Applied AI',
      'stack.item2': 'LLM orchestration',
      'stack.item3': 'Prompt design',
      'stack.item4': 'Product discovery',
      'stack.item5': 'Research & analytics',
      'stack.item6': 'CustDev interviews',
      'stack.item7': 'UX research',
      'stack.item8': 'Product analytics',
      'stack.item9': 'CRM journeys',
      'stack.item10': 'API integrations',
      'stack.item11': 'MVP design',
      'stack.item12': 'Growth systems',
      'stack.item13': 'Content engines',
      'stack.item14': 'Workflow automation',
      'career.kicker': 'Карьерный путь',
      'career.title': 'Тут можно понять как я дошёл до такой жизни',
      'career.text': 'Общий стаж - более 23 лет',
      'career.button': 'Открыть подробную карьеру',
      'contacts.kicker': 'Контакт',
      'contacts.title': 'Если нужен человек, который соединит смысл, продукт и AI в одну рабочую систему — давай говорить',
      'contacts.text': 'Особенно интересны роли и проекты на стыке AI Product Management, research, стратегической упаковки, growth-механик и внедрения AI в реальные процессы.',
      'footer.copy': '© Виталий Крумин.'
    },
    en: {
      meta_title: 'Vitaliy Krumin — AI Product / Applied AI / Research',
      meta_description: 'Vitaliy Krumin is an AI Product Manager and research-driven strategist. I design and launch applied AI systems, product architectures, CRM flows and growth mechanisms that lead to measurable business outcomes.',
      'brand.role': 'AI Product • Applied AI • Research',
      'nav.value': 'Value',
      'nav.cases': 'Cases',
      'nav.publications': 'Publications',
      'nav.career': 'Career',
      'nav.contacts': 'Contacts',
      'topbar.cta': 'Message me',
      'hero.eyebrow': 'AI Product Manager • Research-driven architect • Applied AI systems',
      'hero.title': 'I connect <span>research</span>, <span>product</span> and <span>applied AI</span> into business systems.',
      'hero.lead': 'I am most useful when a messy challenge needs structure: when an idea must become product architecture, an AI workflow must become a real operating system, and the whole thing must end in adoption, metrics and clear business value.',
      'hero.ctaPrimary': 'Message on Telegram',
      'hero.ctaSecondary': 'See selected cases',
      'hero.ctaTertiary': 'Career path',
      'hero.tag1': 'Applied AI & LLM workflows',
      'hero.tag2': 'Product discovery & MVP design',
      'hero.tag3': 'Research, analytics & hypotheses',
      'hero.tag4': 'CRM, growth & customer journeys',
      'hero.metric1': 'years across product, marketing, growth and development',
      'hero.metric2': 'participants across launched education programs',
      'hero.metric3': 'increase in inbound requests in one content system',
      'portrait.label': 'Portrait / personal presence',
      'portrait.title': 'From research and ideas to product, growth, and AI execution.',
      'portrait.text': 'Strategist, researcher, and product architect for AI-driven systems.',
      'signal.label': 'Where I am especially strong',
      'signal.title': 'Not just about AI. About a system that still works after the demo.',
      'signal.item1': 'Research synthesis',
      'signal.item2': 'Product architecture',
      'signal.item3': 'LLM orchestration',
      'signal.item4': 'CRM scenarios',
      'signal.item5': 'Growth loops',
      'signal.item6': 'MVP delivery',
      'signal.status': 'Open to serious work at the intersection of AI Product, strategy, research and systems design',
      'impact.kicker': 'What you get when I join a project',
      'impact.title': 'Not a collection of smart-sounding words, but a person who can turn chaos into working logic',
      'impact.card1.title': 'I find the signal inside the noise',
      'impact.card1.text': 'I do the research, extract what actually matters from fragmented inputs, and define the real problem plus the highest-leverage growth point.',
      'impact.card2.title': 'I design the architecture of the solution',
      'impact.card2.text': 'I translate ideas into product logic, scenarios, processes, data flows and AI workflows that can actually be launched.',
      'impact.card3.title': 'I carry it through to adoption and impact',
      'impact.card3.text': 'I think beyond the mechanics: adoption, metrics, scale and how the system lives after launch all matter.',
      'cases.kicker': 'Selected cases',
      'cases.title': 'Where product, growth, research and applied AI came together',
      'cases.case1.pill': 'Education + AI + CRM',
      'cases.case1.title': 'Content and AI projects for real estate agents',
      'cases.case1.text': 'I launched education mechanics, a content engine and AI practices for agents. The system was not built for vanity metrics — it was built for requests, leads and deals.',
      'cases.case1.r1': 'audience grew by 70%',
      'cases.case1.r2': 'inbound requests grew 4x',
      'cases.case1.r3': 'deals from social channels doubled',
      'cases.case2.pill': 'Applied AI / Agentic workflow',
      'cases.case2.title': 'AI agent for research and Google Workspace',
      'cases.case2.text': 'I built a working environment on top of Perplexity API and ChatGPT API for research, documents, email, calendar and Drive — as one operational system rather than a bunch of disconnected bots.',
      'cases.case2.r1': 'faster research workflows',
      'cases.case2.r2': 'single entry point for operational scenarios',
      'cases.case2.r3': 'lower manual load in routine processes',
      'cases.case3.pill': 'Product / CRM / Growth',
      'cases.case3.title': 'living.ru — secondary market product and CRM scenarios',
      'cases.case3.text': 'I worked on product lines, regional services and CRM for sales and contact center operations, sitting at the intersection of research, product logic and growth.',
      'cases.case3.r1': 'new product increased average check by 30%',
      'cases.case3.r2': 'deal conversion reached 15%',
      'cases.case3.r3': 'CPC traffic share grew to 30%, CAC dropped by 10%',
      'cases.case4.pill': 'Research / Frameworks',
      'cases.case4.title': 'Applied AI research and original frameworks',
      'cases.case4.text': 'I ran a series of studies, published materials on Zenodo and developed framework thinking around AI, human value, organizational effects and product architecture.',
      'cases.case4.r1': 'DOI-backed publications on Zenodo',
      'cases.case4.r2': 'framework-based thinking instead of random hot takes',
      'cases.case4.r3': 'deep link between research, brand and systems design',
      'pubs.kicker': 'Publications',
      'pubs.title': 'For moments when building is not enough and deeper thinking matters',
      'pubs.note': 'Another line of work is the monograph “Reflective Brand” and a set of original frameworks where AI, identity, behavior and product architecture converge into one system.',
      'stack.kicker': 'Working stack',
      'stack.title': 'A toolkit for building real operating systems, not just nice ideas',
      'stack.item1': 'Applied AI',
      'stack.item2': 'LLM orchestration',
      'stack.item3': 'Prompt design',
      'stack.item4': 'Product discovery',
      'stack.item5': 'Research & analytics',
      'stack.item6': 'CustDev interviews',
      'stack.item7': 'UX research',
      'stack.item8': 'Product analytics',
      'stack.item9': 'CRM journeys',
      'stack.item10': 'API integrations',
      'stack.item11': 'MVP design',
      'stack.item12': 'Growth systems',
      'stack.item13': 'Content engines',
      'stack.item14': 'Workflow automation',
      'career.kicker': 'Career path',
      'career.title': 'Here you can understand how I got to this point in my life.',
      'career.text': 'Total experience - more than 23 years',
      'career.button': 'Open detailed career page',
      'contacts.kicker': 'Contact',
      'contacts.title': 'If you need someone who can connect meaning, product and AI into one working system — let’s talk',
      'contacts.text': 'I am especially interested in roles and projects at the intersection of AI Product Management, research, strategic positioning, growth mechanics and AI adoption in real processes.',
      'footer.copy': '© Vitaliy Krumin.'
    }
  },
  experience: {
    ru: {
      meta_title: 'Карьера — Виталий Крумин',
      meta_description: 'Подробный карьерный путь Виталия Крумина: AI Product, growth, CRM, research, запуск обучающих программ, развитие продуктовых и AI-направлений.',
      'brand.role': 'Карьерная архитектура',
      'nav.cases': 'Кейсы',
      'nav.publications': 'Публикации',
      'nav.contacts': 'Контакты',
      'topbar.back': 'На главную',
      'xpHero.eyebrow': 'Career trajectory',
      'xpHero.title': 'Мой путь',
      'xpHero.lead': 'От менеджера по продажам до AI Product / Applied AI / Research',
      'xpHero.cta1': 'Вернуться на главную',
      'xpHero.cta2': 'Запросить CV по почте',
      'xpSummary.label': 'В нескольких цифрах',
      'xpSummary.metric1': 'лет в маркетинге, развитии, продукте и AI',
      'xpSummary.metric2': 'крупных карьерных этапов',
      'xpSummary.metric3': 'ядра компетенций: research, product, growth systems',
      'xpThemes.kicker': 'Сквозные темы',
      'xpThemes.title': 'Что объединяет почти все этапы карьеры',
      'xpThemes.item1': 'Growth и развитие рынков',
      'xpThemes.item2': 'Партнерские экосистемы',
      'xpThemes.item3': 'Продуктовая логика',
      'xpThemes.item4': 'CRM-системы',
      'xpThemes.item5': 'Research-интервью',
      'xpThemes.item6': 'Обучающие продукты',
      'xpThemes.item7': 'Внедрение AI',
      'xpThemes.item8': 'Стратегическая упаковка',
      'xpTimeline.kicker': 'Подробная траектория',
      'xpTimeline.title': 'Разверни нужный этап — без ощущения, что читаешь бесконечное резюме',
      'xp1.company': 'Агентство «Петербургская недвижимость»',
      'xp1.role': 'Маркетолог / контентные и AI-проекты',
      'xp1.text': 'Разрабатываю и внедряю системы продвижения, обучения и использования AI для агентов по недвижимости. Строю механику, которая влияет не только на охваты, но и на лиды, обращения и сделки.',
      'xp1.r1': 'курс по продвижению в соцсетях: 100+ участников, подписчики +70%, обращения x4, сделки x2',
      'xp1.r2': 'курс по prompt engineering: 50+ участников, прирост эффективности в среднем на 30%',
      'xp1.r3': 'методика упаковки личного бренда: 10 кейсов, ER +80%, конверсия в лид до 5%',
      'xp1.r4': 'развитие сервиса для SMM-марафона с AI-коучем, CRM и веб-интерфейсом сопровождения',
      'xp2.company': 'SetlGroup',
      'xp2.role': 'Руководитель по развитию партнерской сети',
      'xp2.text': 'Отвечал за развитие партнерской сети, исследование партнерского опыта и запуск механик роста в регионах. Проводил интервью, проверял гипотезы, проектировал обучающие и growth-инструменты.',
      'xp2.r1': 'провел исследования и интервью, определил приоритеты развития партнерской сети',
      'xp2.r2': 'разработал методику расширения рынка сбыта и фокусировки региональной программы',
      'xp2.r3': 'запустил обучающий продукт для партнеров, увеличив входящие заявки на 15%',
      'xp3.company': 'living.ru / «Умный поиск»',
      'xp3.role': 'Product Manager',
      'xp3.text': 'Отвечал за продуктовые направления “Вторичка”, региональный сервис и CRM для продаж и контакт-центра. Работал с исследованиями, аналитикой, редизайном и сценариями роста.',
      'xp3.r1': 'новый продукт “Вторичка” дал рост среднего чека на 30%',
      'xp3.r2': 'конверсия в сделку выросла до 15%',
      'xp3.r3': 'рост доли CPC-трафика до 30%, снижение CAC на 10%',
      'xp4.company': 'Партнёрский центр БЖР',
      'xp4.role': 'Product Manager',
      'xp4.text': 'Проектировал и запускал продукт для партнеров, внедрял CRM и перестраивал клиентские сценарии для ускорения продаж и повышения операционной эффективности.',
      'xp4.r1': 'создал продукт-агрегатор для партнеров: продажи выросли на 40%',
      'xp4.r2': 'снизил скорость реакции на запрос с 20 до 3 минут',
      'xp5.company': 'ГК «Эталон»',
      'xp5.role': 'Старший менеджер регионального развития',
      'xp5.text': 'Отвечал за маркетинговую стратегию, запуск и развитие представительств, анализ конкурентов, реферальные программы и региональные продажи.',
      'xp5.r1': 'реферальная программа увеличила продажи в регионах на 15%',
      'xp5.r2': 'развернул сеть представительств на Дальнем Востоке и в Якутии',
      'xp5.r3': 'доля региональных продаж достигла 30% от общего объема',
      'footer.copy': '© Виталий Крумин.',
      'footer.home': 'Главная'
    },
    en: {
      meta_title: 'Career — Vitaliy Krumin',
      meta_description: 'Detailed career path of Vitaliy Krumin: AI product, growth, CRM, research, learning programs and product / AI development roles.',
      'brand.role': 'Career architecture',
      'nav.cases': 'Cases',
      'nav.publications': 'Publications',
      'nav.contacts': 'Contacts',
      'topbar.back': 'Home',
      'xpHero.eyebrow': 'Career trajectory',
      'xpHero.title': 'My way',
      'xpHero.lead': 'From Sales Manager to AI Product / Applied AI / Research',
      'xpHero.cta1': 'Back to homepage',
      'xpHero.cta2': 'Request CV by email',
      'xpSummary.label': 'In a few numbers',
      'xpSummary.metric1': 'years across marketing, development, product and AI',
      'xpSummary.metric2': 'major career phases',
      'xpSummary.metric3': 'competency cores: research, product, growth systems',
      'xpThemes.kicker': 'Cross-cutting themes',
      'xpThemes.title': 'What connects almost every stage of the career',
      'xpThemes.item1': 'Growth and market development',
      'xpThemes.item2': 'Partner ecosystems',
      'xpThemes.item3': 'Product logic',
      'xpThemes.item4': 'CRM systems',
      'xpThemes.item5': 'Research interviews',
      'xpThemes.item6': 'Learning products',
      'xpThemes.item7': 'AI adoption',
      'xpThemes.item8': 'Strategic positioning',
      'xpTimeline.kicker': 'Detailed trajectory',
      'xpTimeline.title': 'Open the stage you need — without feeling like you are scrolling through an endless CV',
      'xp1.company': 'Agency “Petersburg Real Estate”',
      'xp1.role': 'Marketing lead / content & AI projects',
      'xp1.text': 'I design and implement promotion, education and AI systems for real estate agents. The mechanics are built not only for reach, but for leads, requests and deals.',
      'xp1.r1': 'social media promotion program: 100+ participants, audience +70%, inbound requests x4, deals x2',
      'xp1.r2': 'prompt engineering program: 50+ participants, average efficiency uplift around 30%',
      'xp1.r3': 'personal brand packaging method: 10 cases, engagement rate +80%, lead conversion up to 5%',
      'xp1.r4': 'development of an SMM marathon service with AI coach, CRM and web interface',
      'xp2.company': 'SetlGroup',
      'xp2.role': 'Head of partner network development',
      'xp2.text': 'I was responsible for partner network development, partner experience research and regional growth mechanisms. I ran interviews, tested hypotheses and designed learning and growth instruments.',
      'xp2.r1': 'ran research and interviews to identify development priorities for the partner network',
      'xp2.r2': 'designed a methodology for market expansion and regional program focus',
      'xp2.r3': 'launched a learning product for partners, increasing inbound requests by 15%',
      'xp3.company': 'living.ru / Smart Search',
      'xp3.role': 'Product Manager',
      'xp3.text': 'I owned the “Secondary Market” product line, regional services and CRM for sales and contact center operations. My work combined research, analytics, redesign and growth scenarios.',
      'xp3.r1': 'the new “Secondary Market” product increased average check by 30%',
      'xp3.r2': 'deal conversion reached 15%',
      'xp3.r3': 'CPC traffic share grew to 30%, CAC dropped by 10%',
      'xp4.company': 'BJR Partner Center',
      'xp4.role': 'Product Manager',
      'xp4.text': 'I designed and launched a product for partners, implemented CRM and rebuilt customer scenarios to accelerate sales and improve operational performance.',
      'xp4.r1': 'built a partner aggregator product: sales grew by 40%',
      'xp4.r2': 'reduced request response time from 20 minutes to 3 minutes',
      'xp5.company': 'Etalon Group',
      'xp5.role': 'Senior regional development manager',
      'xp5.text': 'I was responsible for marketing strategy, launch and development of regional offices, competitor analysis, referral programs and regional sales.',
      'xp5.r1': 'referral program increased regional sales by 15%',
      'xp5.r2': 'launched and scaled representative offices in the Far East and Yakutia',
      'xp5.r3': 'regional sales reached 30% of total sales volume',
      'footer.copy': '© Vitaliy Krumin.',
      'footer.home': 'Home'
    }
  }
};

const page = document.body.dataset.page;
const docDict = translations[page];
const langButtons = [...document.querySelectorAll('[data-lang-btn]')];
const savedLang = localStorage.getItem('site-lang');
const browserLang = navigator.language && navigator.language.toLowerCase().startsWith('ru') ? 'ru' : 'en';
const initialLang = savedLang || browserLang || 'ru';

function applyTranslations(lang) {
  const dict = docDict[lang] || docDict.ru;
  document.documentElement.lang = lang;
  document.title = dict.meta_title;
  const metaDescription = document.querySelector('meta[name="description"]');
  if (metaDescription) metaDescription.setAttribute('content', dict.meta_description);

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.dataset.i18n;
    if (dict[key] !== undefined) node.textContent = dict[key];
  });

  document.querySelectorAll('[data-i18n-html]').forEach((node) => {
    const key = node.dataset.i18nHtml;
    if (dict[key] !== undefined) node.innerHTML = dict[key];
  });

  langButtons.forEach((button) => {
    button.classList.toggle('is-active', button.dataset.langBtn === lang);
  });

  localStorage.setItem('site-lang', lang);
}

langButtons.forEach((button) => {
  button.addEventListener('click', () => applyTranslations(button.dataset.langBtn));
});

applyTranslations(initialLang);

const revealNodes = document.querySelectorAll('[data-reveal]');
if ('IntersectionObserver' in window) {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.14 });

  revealNodes.forEach((node) => observer.observe(node));
} else {
  revealNodes.forEach((node) => node.classList.add('is-visible'));
}
